[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["npm install -g npm@latest", "npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run preview -- --host 0.0.0.0"

